### ISSUE TITLE
Switch component in Filterable Toolbar defaults to True sometimes

### ISSUE THREAD

**Issue by kialam** [RedHatInsights/tower-analytics-frontend#186] opened 2020-07-10 13:51 UTC
**Describe the bug**
![Screen Shot 2020-07-10 at 9 47 56 AM](https://user-images.githubusercontent.com/2293210/87161394-76a8a900-c292-11ea-80ce-e1ff7902965d.png)

On occasion after a hard refresh, the switch component on the filterable toolbar that toggles the "ignore nested wf and jobs" option defaults to `true` instead of `false`. The accompanying console error says:
```
react_devtools_backend.js:6 Warning: Received the string `true` for the boolean attribute `checked`. Although this works, it will not work as expected if you pass the string "false". Did you mean checked={true}?
    in input (created by Switch)
    in label (created by Switch)
    in Switch (created by Context.Consumer)
    in StyledComponent (created by Styled(Switch))
    in Styled(Switch) (created by FilterableToolbar)
    in div (created by FilterableToolbar)
    in div (created by Context.Consumer)
    in div (created by ToolbarContent)
    in ToolbarContent (created by Context.Consumer)
    in StyledComponent (created by Styled(ToolbarContent))
    in Styled(ToolbarContent) (created by FilterableToolbar)
    in div (created by Toolbar)
    in Toolbar (created by FilterableToolbar)
    in FilterableToolbar (created by JobExplorer)
    in div (created by CardBody)
    in CardBody (created by JobExplorer)
    in article (created by Card)
    in Card (created by JobExplorer)
    in section (created by Context.Consumer)
    in Main (created by Connect(Main))
    in Connect(Main) (created by JobExplorer)
    in JobExplorer (created by AsyncComponent)
    in AsyncComponent (created by Route)
    in Route (created by InsightsRoute)
    in InsightsRoute (created by Routes)
    in Switch (created by Routes)
    in Routes (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Route)
    in Route (created by withRouter(Connect(App)))
    in withRouter(Connect(App))
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Provider
```

**To Reproduce**
1. Hard refresh the Job Explorer page.
2. Observe that the toggle for "ignore nested wf and jobs" at the top is set to enabled instead of the default disabled.

**Expected behavior**
Refreshing the Job Explorer page should reset all toggles back to their default states, e.g. the toggle should be disabled.

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6
 - Chrome 83

**Comment by appuk** [comment] 2020-08-18 14:39
will verify this when the Job explorer PR is merged

**Comment by appuk** [comment] 2020-08-24 20:20
I tried to reproduce this issue on CI Beta, I don't see any error in console logs, but looks like the main issue still persists
Steps performed:
1. go to "Job Explorer" page
2. Observe the toggle is disabled by default
3. perform a hard refresh
4. observed that the switch is enabled


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11617351/91091873-3d9b7c80-e625-11ea-9910-f1764a1ffc2c.gif)

@brumik can you please look into this issue, Thanks!

**Comment by brumik** [comment] 2020-08-26 16:11
I think that's what we want. I was just taking care of the error as the bookmarking didn't survives a hard refresh. But maybe I understood the task wrong. Maybe @kialam could help out what she wanted from this task.

**Comment by kialam** [comment] 2020-08-27 15:28
@brumik the switch should default to false if a user refreshes the page. It would only default to true if we:
1. had bookmarking in place
2. they toggled the show nested wf and jobs option to true

**Comment by appuk** [comment] 2020-09-23 20:36
The toggle is disabled after the hard refresh, hence closing the issue

**Closed by appuk** 2020-09-23 20:36 UTC
Labels: bug, needs_test
