### ISSUE TITLE
Job explorer table states are wrong

### ISSUE THREAD

**Issue by Ladas** [RedHatInsights/tower-analytics-frontend#192] opened 2020-07-15 15:01 UTC
**Describe the bug**

We need to be showing the states tower provides which are

```
New
Pending
Waiting
Running
Successful
Failed
Error
Canceled
```

**To Reproduce**
1. Go to job explorer
2. Filter by all states except successful and failed
3. See that e.g. pending and error states are represented as failed

**Expected behavior**
I want to see the tower state name

**Screenshots**

![Screenshot from 2020-07-15 16-14-39](https://user-images.githubusercontent.com/1737058/87561279-ba4d4980-c6bc-11ea-9e03-280ef80930c9.png)

**Comment by kialam** [comment] 2020-07-15 15:03
@trahman73 do you think it makes sense to refactor the existing status component to reflect these job states, or should we just build out the new status pills in the mockups to support them:
![Screen Shot 2020-07-15 at 11 02 56 AM](https://user-images.githubusercontent.com/2293210/87561517-d0daad00-c68a-11ea-8dbb-e9d9b2aa5cd5.png)

**Comment by trahman73** [comment] 2020-07-15 15:10
@kialam lets map and build out the new status pills

**Comment by trahman73** [comment] 2020-07-15 20:05
![image](https://user-images.githubusercontent.com/13351591/87590587-03999b00-c6b5-11ea-877f-5922258b2ad3.png)

**Comment by benthomasson** [comment] 2020-07-22 17:13
We should only show terminal states in Automation Analytics because of the delay caused by periodic uploads.   We should only show these states for jobs:

- Successful
- Failed
- Error
- Canceled

Other states should be hidden until we get a real-time feed from Tower.

**Comment by Ladas** [comment] 2020-07-22 17:30
@benthomasson right, we were talking about that in another issue with @wenottingham , that we are not sure what is the last non-terminal state https://github.com/RedHatInsights/tower-analytics-backend/issues/356#issuecomment-617834471

But we should still show that the job didn't finish, since we can detect that. (you can set tower to send payload every 15 minutes now?) 15 mins is kind of realtime :-)


So the issue is more of that if the job is in state `running` for 5 days, our DB can have `pending` or `waiting` in some cases, but we can quite accurately say the job hasn't finished for 5 days.

**Comment by Ladas** [comment] 2020-07-22 17:45
@wenottingham ah, we haven't backported https://github.com/ansible/tower/pull/4180 https://github.com/ansible/tower/pull/4179 , so for tower < 3.7, we'll not receive the job updated status if it finishes at all :-D

We should get some eyes on these again (it is quite a big bug indeed)

**Comment by benthomasson** [comment] 2020-07-22 17:53
I am trying to decide if this bug makes the cut for v1 (1.1.0) or gets bumped to v2 (1.2.0) of the job explorer.   The full solution might be too much work for 1.1.0.

**Comment by Ladas** [comment] 2020-07-22 18:02
@benthomasson well, we can add all the icons for 1.1, since we have them and mention in docs note that `captured non terminal states for jobs may not be accurate` :-)

And we can figure out for 1.2 what to do. We won't ever get accurate non terminal states from tower, unless tower fetches the data based on `modified` timestamp, but `modified` is not indexed in tower DB, so it will likely not happen. (or it wouldn't get backported)

We can get a pretty good at guessing though, we can move nonterminal job state to `running`, if it's not finished but has some host task there :-)

**Comment by appuk** [comment] 2020-09-09 14:31
the job explorer page now correctly displays the job status, hence closing the issue
![image](https://user-images.githubusercontent.com/11617351/92611892-4461fa80-f287-11ea-87a1-2a098f5ece63.png)

![image](https://user-images.githubusercontent.com/11617351/92611932-504dbc80-f287-11ea-9a5b-34d61d44eba8.png)

**Closed by appuk** 2020-09-09 14:31 UTC
Labels: bug, needs_test
