### ISSUE TITLE
Total jobs change after deleting and re adding the same status filter

### ISSUE THREAD

**Issue by brumik** [RedHatInsights/tower-analytics-frontend#267] opened 2020-09-15 13:49 UTC
**Describe the bug**
The total number on the job explorer page changes after modifying the status filter.

**To Reproduce**
1. Go to clusters page -> top templates modal
2. Click on view all
3. You see the total number in the results in the job explorer page
3. Delete one status and add it back
4. The number of total results is different than it was from clicking the link 

**Expected behavior**
The total number of results should match

**Screenshots**
** After clicking the link**
![Screenshot from 2020-09-15 15-37-42](https://user-images.githubusercontent.com/8531681/93218568-a67c9d00-f76a-11ea-8202-a0bf0c5d22a1.png)
**Deletting the status `New` and re adding it**
![Screenshot from 2020-09-15 15-48-06](https://user-images.githubusercontent.com/8531681/93218761-ddeb4980-f76a-11ea-8421-7cc923025cd7.png)

**Comment by Ladas** [comment] 2020-09-15 15:06
@brumik so the `view all` sends `start_date` and `end_date` , but then working fir filters only last_30_days is active.

The issue is on API side, since `last_30_days` returns 31 days as <today - 30 days, today>

I am gonna fix the API to return <today - 29 days, today> when sending `last_30_days`, which results in 30 days as expected. (@kialam @brumik does it make sense?)

**Comment by Ladas** [comment] 2020-09-15 15:22
@brumik @kialam ah ok scratch the ^, the view all probably returns a month ago exactly? Since 15.8 - 15.9 is 32 days, so we'll need to show the `custom` and the dates after clicking on view_all, not `last_30_days` since that doesn't match the v0_1 filter

**Comment by brumik** [comment] 2020-09-17 14:08
So updating the API to v1 where we link to job explorer will also solve this issue, since then we will get the same?

**Comment by Ladas** [comment] 2020-09-17 14:23
@brumik yeah, updating everything to v1 means we'll send the same set of filters around. So the result should be always consistent across pages (and if not, it will be a backend bug :-D )

**Comment by benthomasson** [comment] 2020-09-22 13:00
@Ladas should this fix be included in 1.1.0?

**Comment by Ladas** [comment] 2020-09-22 13:04
@benthomasson yes, it's a bug on 1.1

**Comment by jeanetteobr** [comment] 2020-09-23 14:22
Hello, all! The "Total Jobs" badge should be removed per #238:

> Remove "Total Count" section at the top header.
Mockup:
![image](https://user-images.githubusercontent.com/32466511/94024343-4b0f6800-fd85-11ea-90b8-7f96c1fa86c0.png)

There's a PR open that handles this among other updates here: https://github.com/RedHatInsights/tower-analytics-frontend/pull/268.

**Comment by Ladas** [comment] 2020-09-30 08:35
@jeanetteobr this issue is about the `Total jobs` being wrong due to wrong date range passed when going from template modal. The total jobs is still exposed as part of `1-5 of 5`, so the `of 5` is total jobs, so that number needs to match according to the bug description

**Comment by kialam** [comment] 2020-10-01 15:59
This appears to be fixed: https://github.com/RedHatInsights/tower-analytics-frontend/commit/12df4fa96c703db89ba8eaff555b78d81add3d60

**Comment by appuk** [comment] 2020-10-05 20:01
Deleting and Re adding the filter doesn't change the number of jobs anymore, hence closing

**Closed by appuk** 2020-10-05 20:01 UTC
Labels: bug, needs_test
