### ISSUE TITLE
ROI - Date selector bug

### ISSUE THREAD

**Issue by brumik** [RedHatInsights/tower-analytics-frontend#234] opened 2020-08-06 12:46 UTC
**Note:** I did the found it on the job_expoler-list-view branch, not on master`

**Describe the bug**
Sometimes switching to `Year` or `Year to Date` selection in ROI calculator makes the graph bars disappear. The text and the axes are loaded, just the bars are gone. Switching to smaller ranges fixes that and it is not happening all the time but from my test around 1/3 times.

**To Reproduce**
1. Go to Automation Calculator
2. Play with date selection a bit.

**Expected behavior**
It should render the graph correctly.

**Screenshots**
![Screencast from 08-06-2020 02_43_50 PM](https://user-images.githubusercontent.com/8531681/89533215-5f0e0300-d7f3-11ea-9d37-ee28d1a3dc96.gif)

**Desktop (please complete the following information):**
 - OS: Fedora 32
 - Browser Chrome
 - Version lastes

**Comment by kialam** [comment] 2020-08-06 16:13
@brumik I checked out the `jo_job-explorer-list-view` branch and cannot seem to reproduce this. Can you tell me if there are any console or network errors?

**Comment by jctanner** [comment] 2020-08-06 17:31
@brumik can you also share what your setup is? I'd like to see the spandx you are using so I can get a sense of what backend is in use.

**Comment by brumik** [comment] 2020-08-07 04:08
I am running full stack with backend branch `feature_job_explorer_api_with_proper_rollups` and with `spandx.config`:

I cannot reproduce with the production backend.

```
const localhost = (process.env.PLATFORM === 'linux') ? 'localhost' : 'host.docker.internal';
const backend = 'fastapi';

module.exports = {
    routes: {
        '/apps/automation-analytics': { host: `https://${localhost}:8002` },
        '/ansible/automation-analytics': { host: `https://${localhost}:8002` },
        '/beta/ansible/automation-analytics': { host: `https://${localhost}:8002` },
        '/beta/config': { host: `http://${localhost}:8889` },
        '/api/tower-analytics': { host: `http://${backend}:8004` }
    }
};
```

**Comment by jctanner** [comment] 2020-08-10 13:43
@brumik can you test this patch to see if it works around the issue?

```
diff --git a/src/Containers/AutomationCalculator/AutomationCalculator.js b/src/Containers/AutomationCalculator/AutomationCalculator.js
index 9dff49a..960f9a5 100644
--- a/src/Containers/AutomationCalculator/AutomationCalculator.js
+++ b/src/Containers/AutomationCalculator/AutomationCalculator.js
@@ -275,12 +275,16 @@ export const useAutomationFormula = () => {
     const [ totalSavings, setTotalSavings ] = useState(0);
     const [ unfilteredData, setUnfilteredData ] = useState([]);
     const [ formattedData, setFormattedData ] = useState([]);
+    const [ mangledData, setMangledData ] = useState([]);
     const [ templatesList, setTemplatesList ] = useState([]);
     const [ roiData, setRoiData ] = useState([]);
     const [ selectedIds, setSelectedIds ] = useState([]);
 
     const { formatData } = automationCalculatorMethods();
 
+    useEffect(() => {
+    }, [ mangledData ]);
+
     useEffect(() => {
         let data = [ ...formattedData ];
         let total = 0;
@@ -304,6 +308,9 @@ export const useAutomationFormula = () => {
         .toString()
         .replace(/\B(?=(\d{3})+(?!\d))/g, ',');
         setTotalSavings('$' + totalWithCommas);
+
+        setMangledData([ ...data ]);
+
     }, [ formattedData, costAutomation, costManual ]);
 
     useEffect(() => {
```

**Comment by jctanner** [comment] 2020-08-10 17:48
I can reproduce the bug on macos

![image](https://user-images.githubusercontent.com/1869705/89813441-b4a62080-db0f-11ea-9261-2f8ebfa6f4e8.png)

* macos 10.14.4
* docker-desktop 2.3.4
* chrome 84
* nvm use 10.21
* DEBUG='express:*' npm start

**Comment by jctanner** [comment] 2020-08-10 18:11
Another workaround ...

```
diff --git a/src/Containers/AutomationCalculator/AutomationCalculator.js b/src/Containers/AutomationCalculator/AutomationCalculator.js
index 9dff49a..58e3577 100644
--- a/src/Containers/AutomationCalculator/AutomationCalculator.js
+++ b/src/Containers/AutomationCalculator/AutomationCalculator.js
@@ -400,6 +400,7 @@ const AutomationCalculator = () => {
             });
             getData().then(({ templates: roiData = []}) => {
                 if (!ignore) {
+                    setRoiData([]);
                     setRoiData(roiData);
                     setIsLoading(false);
                 }
```

**Comment by jctanner** [comment] 2020-08-11 16:33
I'm pretty sure this is the same issue as described here: https://kentcdodds.com/blog/understanding-reacts-key-prop

I'm able to "fix" the issue in a few ways:

A) set roidata to an intermediate empty list so that the shadow dom definitely has changes
B) add a hidden div to the render function with a random/unique id
C) add a key to the TopTemplateSavings chart with a random/unique id

**Comment by benthomasson** [comment] 2020-08-11 20:55
When I see this occur I see this in the network tab:
GET | https://prod.foo.redhat.com:1337/api/tower-analytics/roi_templates/?startDate=2019-08-11&endDate=2020-08-11

**Comment by brumik** [comment] 2020-08-12 13:20
Hm, yeah, JFYI (https://github.com/RedHatInsights/tower-analytics-frontend/pull/230 - if this beast ever gets merged :worried: ) and with my changes, I cannot reproduce the problem. 

Most probably it would be a performance hog but I think we can also do a deep comparison in the chart on `willReceiveProps` if the data changes and if it is not just don't rerender. 

I would say that the most sensible solution if we have no other options, would be C.

**Comment by benthomasson** [comment] 2020-08-12 13:36
It is not just the chart rendering incorrectly.  Other things are not rendering correctly either.   
<img width="416" alt="Screen Shot 2020-08-11 at 5 47 52 PM" src="https://user-images.githubusercontent.com/44381/90021447-47190200-dc7f-11ea-9c19-18b200362c95.png">
<img width="315" alt="Screen Shot 2020-08-11 at 5 47 20 PM" src="https://user-images.githubusercontent.com/44381/90021454-497b5c00-dc7f-11ea-80ad-1e8442ca1f3f.png">

**Comment by benthomasson** [comment] 2020-08-12 13:37
It only reproduces when using `make up`.   I cannot reproduce it when using `make ui`

**Comment by benthomasson** [comment] 2020-08-12 13:38
It is very deterministic.  Switching between `Past Year` and `Past Year To Date` will cause it every time.

**Comment by brumik** [comment] 2020-08-12 13:38
Oh, I did not know. 

I am bringing up my backend with `docker-compose -f ./tower-analytics-backend/local_ui_dev.yml up -V`

**Comment by brumik** [comment] 2020-08-12 13:40
Yes, @benthomasson because for both options the data is the same. If we had more data for the year than for a quarter we would not see this happening I think. (It was talked about on slack if I remember)

**Comment by jctanner** [comment] 2020-08-12 13:45
@benthomasson are you seeing the issue on mac or linux?

**Comment by benthomasson** [comment] 2020-08-12 15:35
The backend and frontend run on linux.   I am using firefox on a Mac to connect to my development machine.

**Comment by benthomasson** [comment] 2020-08-12 17:23
This is a weird bug.   Only the delta is 0.  Everything else is fine.

Normal:


<img width="341" alt="Screen Shot 2020-08-12 at 1 21 21 PM" src="https://user-images.githubusercontent.com/44381/90046862-0b8e3000-dc9f-11ea-9c8b-27d2ea007b62.png">

Bug:

<img width="347" alt="Screen Shot 2020-08-12 at 1 22 45 PM" src="https://user-images.githubusercontent.com/44381/90046865-0df08a00-dc9f-11ea-87a7-b6b217e4ac2d.png">

**Comment by benthomasson** [comment] 2020-08-12 17:25
But delta is fine before the templating starts:

<img width="551" alt="Screen Shot 2020-08-12 at 1 24 48 PM" src="https://user-images.githubusercontent.com/44381/90047008-3a0c0b00-dc9f-11ea-810b-614c989053b1.png">

**Comment by benthomasson** [comment] 2020-08-13 13:35
I determined that the problem is due to several useEffect calls that watch intermediate data structures.  In this case the formattedData data structure does not update and this code is never called: 

>   287     useEffect(() => {
>   288         let data = [ ...formattedData ];
>   289         let total = 0;
>   290         let costAutomationPerHour;
>   291         let costManualPerHour;
>   292 
>   293         data.forEach((datum) => {
>   294             costAutomationPerHour =
>   295         convertSecondsToHours(datum.successful_elapsed_sum) * costAutomation;
>   296             costManualPerHour =
>   297         convertSecondsToHours(datum.calculations[0].avg_run) *
>   298         datum.successful_host_run_count *
>   299         costManual;
>   300             total += calculateDelta(costAutomationPerHour, costManualPerHour);
>   301             datum.delta = calculateDelta(costAutomationPerHour, costManualPerHour);
>   302             datum.calculations[0].cost = costManualPerHour;
>   303             datum.calculations[1].cost = costAutomationPerHour;
>   304         });
>   305         const totalWithCommas = total
>   306         .toFixed(2)
>   307         .toString()
>   308         .replace(/\B(?=(\d{3})+(?!\d))/g, ',');
>   309         setTotalSavings('$' + totalWithCommas);
>   310     }, [ formattedData, costAutomation, costManual ]);

**Comment by kialam** [comment] 2020-08-13 14:21
As @benthomasson stated, I can reproduce the bug with `make up` but not `make ui`. The data payload is the same in both setups and the components update. Seems strange to me that `useEffect` runs correctly for one setup but not another.

![diff](https://user-images.githubusercontent.com/2293210/90146197-c1fd1e00-dd4e-11ea-8e05-4f240ade979b.gif)

**Comment by jctanner** [comment] 2020-09-08 13:18
resolved by https://github.com/RedHatInsights/tower-analytics-frontend/pull/247

**Comment by appuk** [comment] 2020-09-23 21:07
I tried to verify the fix with a user that has same data set for Past Year and Past Year to Date, and the graph and values are loading correctly as expected
hence, closing

**Closed by appuk** 2020-09-23 21:07 UTC
Labels: bug, needs_test
